name: Spellcheck Markdown

on: [push, pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install codespell
        run: pip install codespell

      - name: Filter files and run codespell
        run: |
          # Create a temporary file to store words to ignore
          TEMP_IGNORE_FILE=$(mktemp)

          # Ignore Acronyms (all caps), with and without trailing punctuation
          grep -oE '\b[A-Z][A-Z]+[^a-zA-Z]' $(git ls-files '*.md') | sort -u >> $TEMP_IGNORE_FILE

          # Ignore Proper nouns (capitalized first letter), with and without trailing punctuation
          grep -oE '\b[A-Z][a-z]+[^a-zA-Z]' $(git ls-files '*.md') | sort -u >> $TEMP_IGNORE_FILE

          # Remove duplicate entries
          sort -u $TEMP_IGNORE_FILE -o $TEMP_IGNORE_FILE

          # Run codespell on Markdown files with dynamically generated ignore list
          codespell --ignore-words-list="$(tr '\n' ',' < $TEMP_IGNORE_FILE)" $(git ls-files '*.md')

          # Clean up
          rm $TEMP_IGNORE_FILE
