name: Spellcheck

on: [push, pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install codespell
        run: pip install codespell

      - name: Filter files and run codespell
        run: |
          # Create a temporary file to store words to ignore
          TEMP_IGNORE_FILE=$(mktemp)

          # Extract all fully capitalized words from the codebase and add them to the ignore list
          grep -oE '\b[A-Z][A-Z]+\b' $(git ls-files) | sort -u >> $TEMP_IGNORE_FILE

          # Remove duplicate entries
          sort -u $TEMP_IGNORE_FILE -o $TEMP_IGNORE_FILE

          # Run codespell with dynamically generated ignore list
          codespell --ignore-words-list="$(tr '\n' ',' < $TEMP_IGNORE_FILE)"

          # Clean up
          rm $TEMP_IGNORE_FILE
